### ISSUE TITLE
Follow XDG Base Directory Specification

### ISSUE THREAD

**Issue by scoronado12** [smason1995/remote#2]
`dotfiles` are nice. However, a program as small as `remote` should easily conform with the XDG Base Directory Spec.
https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html

A lighter read of the spec is here

https://wiki.archlinux.org/index.php/XDG_Base_Directory

**Comment by smason1995** [comment]
I have looked into this, and implemented inside the latest version under the code/ directory

**Comment by smason1995** [comment]
Have implemented inside the latest version under the code directory
